---
title: "Chapter 3"
output: html_notebook
---

# 3 효율적인 프로그래밍

```{r}
library("compiler")
library("memoise")
```

## 3.1 효율적인 프로그래밍을 위한 상위 5가지 팁

1.  벡터를 성장시키지 않도록 주의하십시오.

2.  가능하면 코드를 벡터화하십시오.

3.  적절한 경우 요인을 사용합니다.

4.  변수를 캐싱하여 불필요한 계산을 피하십시오.

5.  손쉬운 성능 향상을 위한 바이트 컴파일 패키지.

## 3.2 일반적인 조언

```{r}
n <- 100000000
x <- rnorm(n)
system.time(x <- x + 1)
system.time({
  for (i in seq_len(n)) {
    x[i] <- x[i] + 1
  }
})
```

### 3.2.1 메모리 할당

```{r}
method1 <- function(n) {
  vec <- NULL # Or vec = c()
  for (i in seq_len(n)) {
    vec <- c(vec, i)
  }
  vec
}

method2 <- function(n) {
  vec <- numeric(n)
  for (i in seq_len(n)) {
    vec[i] <- i
  }
  vec
}

method3 <- function(n) seq_len(n)
```

```{r}
n <- 1e5
microbenchmark::microbenchmark(
  times = 1, unit = "s",
  method1(n), method2(n), method3(n)
)
```

### 3.2.2 벡터화된 코드

```{r}
monte_carlo <- function(N) {
  hits <- 0
  for (i in seq_len(N)) {
    u1 <- runif(1)
    u2 <- runif(1)
    if (u1^2 > u2) {
      hits <- hits + 1
    }
  }
  return(hits / N)
}

monte_carlo_vec <- function(N) sum(runif(N)^2 > runif(N)) / N

N <- 500000
system.time(monte_carlo(N))
system.time(monte_carlo_vec(N))
```

## 3.3 사용자와의 커뮤니케이션

```{r}
good <- try(1 + 1, silent = TRUE)
good
```

```{r}
bad <- try(1 + "1", silent = TRUE)
bad
```

**경고**

```{r}
mean(NULL)
```

```{r}
suppressWarnings(mean(NULL))
```

### 3.3.1 보이지 않는 반환값

```{r}
a <- hist(rnorm(1000))
str(a)
```

## 3.4 요인

```{r}
x <- 4:6
c(x)
```

```{r}
as.numeric(factor(x))
```

```{r}
m <- month.name[c(1, 12, 3)]
fac_m <- factor(m, levels = month.name)
sort(fac_m)
```
